ftea/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from ftea import views


app_name = 'ftea'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('welcome/', views.Welcome.as_view(), name='welcome'),
    path('project/<int:id>', views.Project_View.as_view(), name='project'),
    path('addproject/', views.ProjectCreate.as_view(), name='add_project'),
    path('task/<int:id>', views.Task_View.as_view(), name='task'),
    path('addtask/', views.TaskCreate.as_view(), name='add_task'),
    path('adddiary/', views.DiaryCreate.as_view(), name='add_diary'),
    path('diary/', views.DiaryList.as_view(), name='diary'),
    path('translator/', views.Translator.as_view(), name='translator'),
    path('ocr/', views.OcrTest.as_view(), name='ocr'),
    path('top-praca/', views.Top_Praca.as_view(), name='top-praca'),
    path('ff/', views.FF.as_view(), name='ff'),
    path('ff-ajax/', views.FF_ajax.as_view(), name='ff-ajax'),
    path('ff-banners/', views.FF_banners.as_view(), name='ff-banners'),
    path('lotko/', views.Lotko.as_view(), name='lotko'),
    ]

ftea/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from ftea import models
# from bootstrap_datepicker_plus import DatePickerInput


class TranslateForm(forms.Form):
    Word_pol = forms.CharField(max_length=500, required=False)
    Word_eng = forms.CharField(max_length=500, required=False)

class ContactForm(forms.Form):
    name = forms.CharField(max_length=500, required=True)
    email = forms.EmailField(max_length=500, required=True)
    message = forms.CharField(max_length=900, required=True)

class TaskForm(forms.ModelForm):
    class Meta:
       model = models.Task
       fields = ('task_name','task_description', 'task_status', 'task_project', 'deadline', 'task_prio',)
       # widgets = {
       #     # 'deadline': DatePickerInput(),  # default date-format %m/%d/%Y will be used
       #     'deadline': DatePickerInput(format='%Y-%m-%d'),  # specify date-frmat
       # }
       deadline = forms.DateField(
           widget=forms.DateInput(
               attrs={
                   'type': 'date',
               }
           )
       )

    def __init__(self, *args, **kwargs):
       user = kwargs.pop('user')
       super(TaskForm, self).__init__(*args, **kwargs)
       self.fields['task_project'].queryset = models.Project.objects.filter(project_user=user)

class DiaryForm(forms.ModelForm):
    class Meta:
       model = models.Diary
       fields = ('diary_name', 'diary_description', 'diary_motto',)

class TaskForm_change_status(forms.ModelForm):
    class Meta:
       model = models.Task
       fields = ('task_status',)

class AddTask(forms.ModelForm):
    class Meta:
       model = models.Task
       fields = ('task_name', 'task_description', 'task_notes', 'deadline', 'task_prio', 'task_project','task_status', 'task_type',)
       # widgets = {
       #     # 'deadline': DatePickerInput(),  # default date-format %m/%d/%Y will be used
       #     'deadline': DatePickerInput(format='%Y-%m-%d'),  # specify date-frmat
       # }

class AddDiary(forms.ModelForm):
    class Meta:
       model = models.Diary
       fields = ('diary_name', 'diary_description', 'diary_motto',)


class ChangeTaskStatus(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = ('task_status', 'id',)

ftea/views.py
import json

import django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView
from datetime import datetime, timedelta, date
from ftea.forms import TranslateForm
from googletrans import Translator as GoogleTrans
from ftea import models, forms
from django.db.models import Q
from django.core.mail import send_mail, BadHeaderError
import pytesseract
from PIL import Image
import os
from jira import JIRA
from ftea import jira_connect, jira_filters
from django.contrib.auth.models import User
import xlwt
from bs4 import BeautifulSoup
import requests


# Create your views here.
class Index(View):
    def get(self, request):
        if request.is_ajax():
            pass
        else:
            form = forms.ContactForm
            ctx = {"form": form}
        return render(request, 'ftea/index1.html', ctx)

    def post(self, request):
        form = forms.ContactForm(request.POST)
        if form.is_valid():
            name = request.POST.get('name')
            email = request.POST.get('email')
            message = request.POST.get('message')
            email = "Kontakt od: {}, email: {}, wiadomosc: {}".format(name, email, message)
            try:
                send_mail('Kontakt z 4tea.pl', email, 'lukasz.szlaszynski@4tea.pl', ['lukasz.szlaszynski@4tea.pl'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            mess = "Mess sent"
        return render(request, 'ftea/index1.html')

class Translator(View):
    def get(self, request):
        translator = GoogleTrans()
        if request.is_ajax():
            if request.GET.get('request_type') == "translator":
                lang_in = ''
                lang_out = ''
                if request.GET.get('lang') == "eng":
                    lang_in = 'en'
                    lang_out = 'pl'
                elif request.GET.get('lang') == "pol":
                    lang_in = 'pl'
                    lang_out = 'en'
                word = translator.translate(request.GET.get('word'), dest=lang_out, src=lang_in)
                print('word')
                ctx = {'word': word.text,
                       'lang': lang_out}
                return HttpResponse(json.dumps(ctx))
            elif request.GET.get('request_type') == "delete_record":
                id_to_delete = request.GET.get("id")
                delete_word = models.Translator.objects.get(id=id_to_delete)
                delete_word.delete()
                ctx = {'status': 200}
                return HttpResponse(json.dumps(ctx))
            elif request.GET.get('request_type') == "add_to_db":
                eng_word = request.GET.get('word_eng')
                pol_word = request.GET.get('word_pol')
                check_if_exist = models.Translator.objects.filter(translator_user=request.user,
                                                                  word_eng=eng_word,
                                                                  word_pol=pol_word).exists()
                if check_if_exist:
                    ctx = {"new_id": "already_exist"}
                else:
                    new_word = models.Translator(translator_user=request.user,
                                                 word_eng=eng_word,
                                                 word_pol=pol_word)
                    new_word.save()
                    new_id = new_word.pk
                    ctx = {"en": eng_word,
                           "pl": pol_word,
                           "new_id": new_id}
                return HttpResponse(json.dumps(ctx))
        else:
            if request.user.is_authenticated:
                all_words = models.Translator.objects.filter(translator_user=request.user)
            else:
                all_words = {}
            ctx = {'all_words': all_words}
            return render(request, 'ftea/translator.html', ctx)

    def post(self, request):
        if request.POST.get('Word_eng') and request.POST.get('Word_pol'):
            pol_word = request.POST.get('Word_pol')
            eng_word = request.POST.get('Word_eng')
            new_word = models.Translator(translator_user=request.user,
                                         word_eng=eng_word,
                                         word_pol=pol_word)
            new_word.save()
        else:
            pass
        all_words = models.Translator.objects.order_by('pk')
        ctx = {'all_words': all_words}
        return render(request, 'ftea/translator.html', ctx)

class Welcome(LoginRequiredMixin, View):
    add_task_form = forms.AddTask
    status_form = forms.ChangeTaskStatus
    template = 'ftea/welcome.html'

    def get(self, request):
        if request.user.groups.filter(name__in=['FF']).exists():
            return redirect("ftea:ff")
        elif request.user.groups.filter(name__in=['TP']).exists():
            return redirect("ftea:top-praca")
        else:
            todays_date = date.today()
            next_seven_days = todays_date + timedelta(days=7)
            next_30_days = todays_date + timedelta(days=30)
            last_twenty_days = todays_date - timedelta(days=20)
            first_date = todays_date - timedelta(days=99999)
            yesterday = todays_date - timedelta(days=1)
            #all projects
            projects = models.Project.objects.filter(project_user=request.user)
            #expired Task
            expired_tasks = models.Task.objects.filter(deadline__range=(first_date, yesterday)).filter(
                task_project__project_user=request.user).exclude(task_status='done').exclude(task_status='hold').order_by("deadline")
            #open Task
            open_tasks = models.Task.objects.filter(deadline__range=(todays_date, next_seven_days)).filter(
                task_project__project_user=request.user).exclude(task_status='done').exclude(task_status='hold').order_by("deadline")
            closed_tasks_last_twenty_days = models.Task.objects.filter(deadline__range=(last_twenty_days, todays_date)).filter(
                task_project__project_user=request.user).exclude(task_status='to do').exclude(task_status='in progres').order_by("-updated_at")
            ctx = {
                "projects": projects,
                "expired_tasks": expired_tasks,
                "open_tasks": open_tasks,
                "form": self.add_task_form,
                "status_form": self.status_form,
                "closed_tasks_last_twenty_days": closed_tasks_last_twenty_days
            }
            return render(request, self.template, ctx)

    def post(self, request):
        add_task_form = self.add_task_form(request.POST)
        status_form = self.status_form(request.POST)
        if add_task_form.is_valid():
            p = add_task_form.save()
            return redirect("ftea:welcome")
        if request.POST.get('task_id'):
            task_id = request.POST.get('task_id')
            new_task_status = request.POST.get('task_status')
            task_to_update = models.Task.objects.get(id=task_id)
            task_to_update.task_status = new_task_status
            task_to_update.save()
            return redirect("ftea:welcome")
        return HttpResponse('co poszło nie tak')



class Project_View(LoginRequiredMixin, View):
    def get(self, request, id):
        project = models.Project.objects.filter(id=id)
        ctx = {'project': project}
        return render(request, 'ftea/project.html', ctx)

#addproject/
class ProjectCreate(LoginRequiredMixin, CreateView):
    model = models.Project
    fields = ['project_name','project_description', 'project_status']
    success_url = reverse_lazy("ftea:welcome")

    def form_valid(self, form):
        form.instance.project_user = self.request.user
        return super().form_valid(form)

class Task_View(LoginRequiredMixin, View):
    def get(self, request, id):
        task = models.Task.objects.filter(id=id)
        form_class = forms.TaskForm_change_status
        ctx = {'task': task,
               'form_class': form_class}
        return render(request, 'ftea/task.html', ctx)

    def post(self, request, id):
        #if request.POST.get('Word_eng')
        print(request.POST.get('task_status'))
        change_task_status = models.Task.objects.filter(id=id)
        change_task_status(task_status=request.POST.get('task_status')).save()
        print(change_task_status)
        return HttpResponse("działa")

class TaskCreate(CreateView):
    form_class = forms.TaskForm
    template_name = 'ftea/tasks_form.html'
    success_url = reverse_lazy("ftea:welcome")

    def get_form_kwargs(self):
        kwargs = super(TaskCreate, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.project_user = self.request.user
        return super().form_valid(form)

#dziennik
#wpis tworzenie
class DiaryCreate(CreateView):
    form_class = forms.DiaryForm
    template_name = 'ftea/diary_form.html'
    success_url = reverse_lazy("ftea:welcome")

    def form_valid(self, form):
        form.instance.diary_user = self.request.user
        return super().form_valid(form)

#lista wpisów
class DiaryList(LoginRequiredMixin, View):
    add_diary_form = forms.AddDiary

    def get(self, request):
        diary_list = models.Diary.objects.filter(
            diary_user=request.user)
        ctx = {
            "diary_list": diary_list,
            "form": self.add_diary_form,
        }
        return render(request, 'ftea/diary.html', ctx)


    def post(self, request):
        new_diary = models.Diary(diary_name=request.POST['diary_name'],
                                 diary_description=request.POST['diary_description'],
                                 diary_motto=request.POST['diary_motto'],

ftea/templates/ftea/base.html
{%  load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
        <meta name="keywords" content="">
		<title>4tea</title>
		<!-- Favicon -->
        <link href="{% static 'ftea/images/favicon.png' %}" rel="shortcut icon">
		<!-- CSS -->
{#		<link href="{% static 'ftea/plugins/bootstrap/bootstrap.min.css' %}" rel="stylesheet">#}
		<link href="{% static 'ftea/plugins/owl-carousel/owl.carousel.min.css' %}" rel="stylesheet">
		<link href="{% static 'ftea/plugins/owl-carousel/owl.theme.default.min.css' %}" rel="stylesheet">
		<link href="{% static 'ftea/plugins/magnific-popup/magnific-popup.min.css' %}" rel="stylesheet">
		<link href="{% static 'ftea/css/app.css' %}" rel="stylesheet">
		<!-- Fonts/Icons -->
		<link href="{% static 'ftea/plugins/font-awesome/css/all.css' %}" rel="stylesheet">
		<link href="{% static 'ftea/plugins/themify/themify-icons.min.css' %}" rel="stylesheet">
	</head>
	<body data-preloader="2">

    <header>
			<nav class="navbar navbar-fixed">
				<div class="container-fluid padding-30 padding-top-0 padding-bottom-0">
					<ul class="list-horizontal-unstyled">
						<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
						<li><a href="#"><i class="fab fa-pinterest"></i></a></li>
					</ul>
					<a class="position-center" href="{% url 'ftea:index' %}">
						<h4>4tea</h4>
					</a>
					<!-- Toggle button of Fullscreen menu -->
					<button class="fullscreen-toggle-btn">
			            <span class="lines"></span>
			        </button>
				</div><!-- end container -->
			</nav><!-- end navbar -->

			<div class="fullscreen-menu bg-black"><!-- Add your background class here -->
				<div class="fullscreen-menu-wrapper">
					<div class="position-middle">
						<div class="container">
							<div class="row">
								<div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
									<div class="row">
										<div class="col-12 col-md-6">
											<ul class="list-unstyled">
												<li>
													<h6 class="font-weight-normal uppercase letter-spacing-2px"><a class="hyperlink-7" href="#home">Home</a></h6>
												</li>
												<li>
													<h6 class="font-weight-normal uppercase letter-spacing-2px"><a class="hyperlink-7" href="#about">About</a></h6>
												</li>
                                                {% if user.is_authenticated %}
                                                <li>
													<h6 class="font-weight-normal uppercase letter-spacing-2px"><a class="hyperlink-7" href="{% url 'logout' %}">Log out</a></h6>
												</li>
                                                {% else %}
                                                <li>
													<h6 class="font-weight-normal uppercase letter-spacing-2px"><a class="hyperlink-7" href="{% url 'login' %}">Log in</a></h6>
												</li>
                                                <li>
													<h6 class="font-weight-normal uppercase letter-spacing-2px"><a class="hyperlink-7" href="#">Register</a></h6>
												</li>
                                                {% endif %}
												<li>
													<h6 class="font-weight-normal uppercase letter-spacing-2px"><a class="hyperlink-7" href="{% url 'ftea:welcome' %}">Welcome page</a></h6>
												</li>
                                            			<li>
													<h6 class="font-weight-normal uppercase letter-spacing-2px"><a class="hyperlink-7" href="{% url 'ftea:translator' %}">Translator</a></h6>
												</li>
											</ul>
										</div>
										<div class="col-12 col-md-6">
											<h5 class="font-weight-normal">Contact Info:</h5>
											<ul class="list-unstyled">
												<li>+48 694 037 695</li>
												<li>contact@4tea.pl</li>
												<li>Drzymały 17/6<br/> 05-800 Pruszków</li>
											</ul>
											<ul class="list-horizontal-unstyled icon-sm margin-top-20">
												<li><a class="button-circle button-circle-sm button-border-1px button-circle-outline-white" href="#"><i class="fab fa-facebook-f"></i></a></li>
												<li><a class="button-circle button-circle-sm button-border-1px button-circle-outline-white" href="#"><i class="fab fa-instagram"></i></a></li>
											</ul>
										</div>
									</div><!-- end row(inner) -->
								</div>
							</div><!-- end row(outer) -->
						</div><!-- end container -->
					</div><!-- end position-middle -->
				</div><!-- end fullscreen-menu-wrapper -->
			</div><!-- end fullscreen-menu -->
		</header>


            {% block content %}
        {% endblock %}


		<footer>
			<div class="section-sm">
				<div class="container padding-30 padding-top-0 padding-bottom-0">
					<div class="row align-items-center">
						<div class="col-12 col-md-6">
							<h2>4tea</h2>
							<ul class="list-horizontal-dash margin-top-30">
								<li><a class="hyperlink-7" href="#">FAQ</a></li>
								<li><a class="hyperlink-7" href="#">Careers</a></li>
								<li><a class="hyperlink-7" href="{% url 'ftea:translator' %}">Translator</a></li>
							</ul>
							<p class="margin-top-10">&copy; 2020 4tea, All Rights Reserved.</p>
						</div>
						<div class="col-12 col-md-6 text-md-right">
							<ul class="list-unstyled">
								<li>Drzymały 17/6</li>
								<li>05-800 Pruszków</li>
								<li>contact@4tea.pl</li>
								<li>+48 694 037 695</li>
							</ul>
							<ul class="list-horizontal-unstyled icon-sm margin-top-20">
								<li>
									<a class="button-circle button-circle-sm button-border-1px button-circle-outline-dark button-circle-hover-slide" href="#">
										<i class="fab fa-facebook-f"></i>
										<i class="fab fa-facebook-f"></i>
									</a>
								</li>

								<li>
									<a class="button-circle button-circle-sm button-border-1px button-circle-outline-dark button-circle-hover-slide" href="#">
										<i class="fab fa-instagram"></i>
										<i class="fab fa-instagram"></i>
									</a>
								</li>
							</ul>
						</div>
					</div><!-- end row -->
				</div><!-- end container -->
			</div><!-- end footer -->
		</footer>

		<!-- ***** JAVASCRIPTS ***** -->
		<script src="{% static 'ftea/plugins/jquery.min.js' %}"></script>
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcfbzeDrQKgGyr6s7sLIIkaFZ1Cverc7c"></script>
		<script src="{% static 'ftea/plugins/plugins.js' %}"></script>
		<script src="{% static 'ftea/js/functions.js' %}"></script>
		<script src="{% static 'ftea/js/ajax.js' %}"></script>
	</body>
</html>

ftea/templates/ftea/diary_form.html
                 {% extends 'ftea/base.html' %}
{% load static %}
{% block content %}
    <div class="container" style="margin-top: 100px">
    <h1>Add Today's Entry to your Diary</h1>
    <form action="" method="post" class="mx-auto add_project_form form-style-3">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
    </form>
    </div>
{% endblock %}

ftea/templates/ftea/ff-banners.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ ilosc_banerow }}
</body>
</html>

ftea/templates/ftea/login.html
                 {% extends 'ftea/base.html' %}
{% load static %}
{% block content %}

    <div class="container" style="margin-top:100px">





                    <form method="post" action="{% url 'login' %}" class="form-style-3">
                {% csrf_token %}
<p>{{ form.as_p }}</p>


  <button type="submit" class="btn btn-lg btn-dark">Log in</button>
</form>
</div>

                 {% endblock %}

ftea/templates/ftea/lotko.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{{ data_losowania }}
{{ numer_losowania }}
{{ numerki }}
</body>
</html>

ftea/templates/ftea/project_form.html
                 {% extends 'ftea/base.html' %}
{% load static %}
{% block content %}
    <div class="container" style="margin-top: 100px">
    <h1>Add Project</h1>
    <form action="" method="post" class="mx-auto add_project_form form-style-3">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
    </form>
    </div>
{% endblock %}

ftea/templates/ftea/tasks_form.html
                 {% extends 'ftea/base.html' %}
{% load static %}
{% block content %}
    <div class="container" style="margin-top: 100px">
    <h1>Add Task</h1>
    <form action="" method="post" class="mx-auto add_project_form form-style-3">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
    </form>
    </div>
{% endblock %}

ftea/templates/ftea/welcome.html
{% extends 'ftea/base.html' %}
{% load static %}
{#{% load bootstrap4 %}       {# import bootstrap4/bootstrap3#}
{#{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{#{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{#{{ form.media }}            {# Adds date-picker required JS and CSS #}
{% block content %}
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <script src="{% static 'ftea/js/calendar.js' %}"></script>
<div class="section-lg bg-image bg-image-gradient parallax" style="background-image: url({% static 'ftea/img1/back1.jpg)' %}">
   <!-- Schedule section -->
   <div id="schedule" class="section">
      <div class="container">
         <div class="row col-spacing-40">
            <div class="col-12 col-lg-8">
               <div class="card border-0 box-shadow-with-hover">
                  <div class="card-header bg-dark-lighter border-0 padding-30 d-flex justify-content-between align-items-center">
                     <div>
                        <h5 class="font-weight-normal margin-0"><i class="ti-calendar margin-right-10"></i>Tasks</h5>
                     </div>
                     <div>Active</div>
                  </div>
                  {#                        ------------------------- przeterminowane#}
                  <ul class="list-group list-group-flush">
                     <!-- Button trigger modal -->
                     <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                     Add task
                     </button>
                     <table class="table">
                        <thead class="thead-dark">
                           <tr>
                              <th scope="col">Name</th>
                              <th scope="col">Deadline</th>
                              <th scope="col">Project</th>
                              <th scope="col">Status</th>
                              <th scope="col">Change status</th>
                           </tr>
                        </thead>
                        <tbody>
                           {% for expired_task in expired_tasks %}
                           <tr>
                              <th><a href="{% url 'ftea:task' expired_task.id %}" class="text-danger">{{ expired_task.task_name }}</a></th>
                              <td class="text-danger">{{ expired_task.deadline| date:'Y-m-d' }}</td>
                              <td>{{ expired_task.task_project }}</td>
                              <td>{{ expired_task.task_status }}</td>
                              <td>
                                 <form method="post">
                                    {% csrf_token %}
                                    {% for f in status_form %}
                                    {{ f }}
                                    <input type="hidden" value="{{ expired_task.id }}" name="task_id">
                                    {% endfor %}
                                    <button type="submit">Submit</button>
                                 </form>
                              </td>
                           </tr>
                           {% endfor %}
                           {#                        ------------------------- otwarte#}
                           {% for open_task in open_tasks %}
                           <tr>
                              <th><a href="{% url 'ftea:task' open_task.id %}">{{ open_task.task_name }}</a></th>
                              <td>{{ open_task.deadline| date:'Y-m-d' }}</td>
                              <td>{{ open_task.task_project }}</td>
                              <td>{{ open_task.task_status }}</td>
                              <td>
                                 <form method="post">
                                    {% csrf_token %}
                                    {% for f in status_form %}
                                    {{ f }}
                                    <input type="hidden" value="{{ open_task.id }}" name="task_id">
                                    {% endfor %}
                                    <button type="submit">Submit</button>
                                 </form>
                              </td>
                           </tr>
                           {% endfor %}
                           </tr>
                        </tbody>
                     </table>
                  </ul>
               </div>
            </div>
            <div class="col-12 col-lg-4">
               <div class="card border-0 box-shadow-with-hover">
                  <div class="card-header bg-dark-lighter border-0 padding-30 d-flex justify-content-between align-items-center">
                     <div>
                        <h5 class="font-weight-normal margin-0"><i class="ti-calendar margin-right-10"></i>Projects</h5>
                     </div>
                     <div>Active</div>
                  </div>
                  <ul class="list-group list-group-flush">
                     <a class="btn-dark" href="{% url 'ftea:add_project' %}">Add project</a>
                     {% for project in projects %}
                     <li class="list-group-item project_style padding-10">
                        <a href="{% url 'ftea:project' project.id %}">{{ project.project_name }}</a>
                        <p>{{ project.created_at| date:'Y-m-d' }}</p>
                        <p>{{ project.project_name }}</p>
                        <p>{{ project.project_status }}</p>
                     </li>
                     {% endfor %}
                  </ul>
               </div>
            </div>


         <div class="col-12 col-lg-12">
               <div class="card border-0 box-shadow-with-hover">
                  <div class="card-header bg-dark-lighter border-0 padding-30 d-flex justify-content-between align-items-center">
                     <div>
                        <h5 class="font-weight-normal margin-0"><i class="ti-calendar margin-right-10"></i>Closed tasks last 20</h5>
                     </div>
                     <div>Active</div>
                  </div>
                  {#                        ------------------------- przeterminowane#}
                  <ul class="list-group list-group-flush">
                     <!-- Button trigger modal -->
                     <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                     Add task
                     </button>
                     <table class="table">
                        <thead class="thead-dark">
                           <tr>
                              <th scope="col">Name</th>
                              <th scope="col">Deadline</th>
                              <th scope="col">Project</th>
                              <th scope="col">Status</th>
                              <th scope="col">Change status</th>
                           </tr>
                        </thead>
                        <tbody>
                           {% for closed_task in closed_tasks_last_twenty_days %}
                           <tr>
                              <th><a href="{% url 'ftea:task' closed_task.id %}" class="text-danger">{{ closed_task.task_name }}</a></th>
                              <td class="text-danger">{{ closed_task.deadline| date:'Y-m-d' }}</td>
                              <td>{{ closed_task.task_project }}</td>
                              <td>{{ closed_task.task_status }}</td>
                              <td>
                                 <form method="post">
                                    {% csrf_token %}
                                    {% for f in status_form %}
                                    {{ f }}
                                    <input type="hidden" value="{{ closed_task.id }}" name="task_id">
                                    {% endfor %}
                                    <button type="submit">Submit</button>
                                 <input data-provide="datepicker">
                                 </form>
                              </td>
                           </tr>
                           {% endfor %}
                        </tbody>
                     </table>
                  </ul>
               </div>
            </div>





   </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <form action="" method="post" class="mx-auto add_project_form form-style-3">
               {% csrf_token %}
               {{ form }}
               <input type="submit" class="btn btn-primary" value="Save">
            </form>
         </div>
         <div class="modal-footer">
         </div>
      </div>
   </div>
</div>
   </div>
</div>
{% endblock %}